POST http://localhost:3003/api/anecdotes
content-type: application/json

{
  "content": "If it hurts, do it more often111",
  "author": "Jez Humble111",
  "info": "https://martinf111owler.com/bliki/FrequencyReducesDifficulty.html"
}